### ISSUE TITLE
ESP Board / Flash image

### ISSUE THREAD

**Issue by slimline33** [Hades32/web-tags#1]
Hi, ich bekomme leider keine Antworten auf meine issues  vom ursprünglichen Entwickler daher versuche ich es hier, da du einen fork von original erstellt hast.

Welches Board nutzt du für den ap und gibt es eine Möglichkeit ein fertig kompiliertes Image von dir zu beziehen? Ich versuche mich seit Tagen an dem AP und bekomme ihn leider nicht zum laufen. Habe Probleme mit dem Webserver und komme im VSC nicht vorwärts. 

Hoffe auf eine Antwort

Gruß Christoph

**Comment by Hades32** [comment]
Ist ein Standard ESP32 Dev board. Dieses Repo hier sollte direkt mit PlatformIO deploybar sein. Mehr kann ich mit so einer Fehlerbeschreibung nicht sagen

**Comment by slimline33** [comment]
Danke erstmal.

Ja, ich habe folgende Probleme: einmal den watchdog (https://github.com/atc1441/E-Paper_Pricetags/issues/54) und dann dann hatte ich noch ein Problem, das der Inhalt der Dateien in der Webgui nicht sichtbar war (https://github.com/me-no-dev/ESPAsyncWebServer/issues/1210).

Mein Problem ist (glaube ich) , dass VisualStudio mit PIO beim Erstellen sich die aktuellen Abhängigkeiten zieht und nicht die mitgelieferten im Paket. Daher könnte es auch an denen liegen.

Da ich mit PIO nicht so firm bin und Fehler ausschließen wollte, habe ich habe es dann irgendwann mit der arduino IDE und den mitgelieferten Abhängigkeiten kompilieren können, jedoch löst es dann beim Senden einer Grafik (über den drawer z. B. oder reinen Text) bei mir den watchdog des Async aus. Dieser Fehler ist nur über die serielle Verbindung sichtbar. Der ESP rebootet dann wie zu erwarten. 

Auch dein Repo habe ich versucht. 

Ich habe mich das letzte mal vor 4 Wochen mit dem Projekt beschäftigt und es absolut nicht zum Laufen bekommen.

Mit einem SDR habe ich auch überprüft ob die Frequenzen passen usw... Die Aktivierung habe ich hin bekommen. Sehe auch auf dem Labornetzteil das die Displays arbeiten beim "binden". 

Ich hoffe das war ausführlich genug erstmal. Ich wollte auch gar nicht groß nach Hilfe zur Fehlerbehebung fragen. Trotzdem hat es mich heute nochmal so gefuxt, dass ich mich nochmal damit beschäftige. Hier liegen einige Displays mit 7.5 und wollte sie nur ungern entsorgen 🙈.

Gruß Christoph

**Comment by Hades32** [comment]
Ich denke deine beste Chance ist dann, dass du auf jeden Fall PIO verwendest, und bei allen dependencies den genauen commit einträgst der vor 10 Monaten (oder wann auch immer mein letzter commit war) aktuell war. Dann sollte es passen. Allerdings ist der ganze Code nicht so 100% stabil und timeouts hatte ich auch öfters mal. Aber ohne watchdog...

**Comment by slimline33** [comment]
Ja, wenn es nur so einfach wäre.  Mit timeouts könnte ich umgehen. Dann müsste man evtl. einfach öfters senden.

Alle dependencies sind alt genug und wurden nicht mehr aktualisiert, ausser der ASYNCWebserver branch. Ich weiß absolut nicht wie ich da die Version mit z.B. dem tag 2.0.4-Beta (der ist ca 11 Monate alt) in meine plattformio.ini bekomme. Das scheitert schon daran, da der branch ja der ASYNCWebserver ist und nicht der master.

Wenn ich mir also einen commit ansehe der im ~oktober 2021 eingearbeitet wurde... 72b5331 dann hab ich grundsätzlich fehler bzgl. github beim compilieren:	

in meiner .ini hab ich beim asyncwebserver das mit rein: 

https://github.com/tzapu/WiFiManager.git#feature_asyncwebserver@72b5331

**Comment by Hades32** [comment]
Also da müsste ich auch in der Dokumentation nachschauen. Aber im schlimmsten Fall forkst du einfach das Repo und machst einen branch mit von genau dem commit den du willst und referenzierst den dann.

Und kann man den watchdog nicht ausschalten bzw auf einen deutlich höheren Wert konfigurieren? Ich glaube ich hatte das sogar gemacht, aber ich habe jetzt schon ewig nichts mehr damit gemacht... Sollte ich eigentlich mal wieder...

**Comment by slimline33** [comment]
Habe inzwischen herausbekommen wie man bestimmte Versionen über pio nutzt, jedoch tauchen dann andere Fehler auf 😂

Bzgl watchdog hatte ich versucht async soweit zu bringen das es nicht beide cores nutzt. Dann läuft der Webserver aber nicht mehr.

Es ist eigentlich voll schade das es absolut nicht geht. Erst der Erfolg mit der Aktivierung und dann so viele Kleinigkeiten... Ich hätte so viele Ideen welche man mit den displays anstellen könnte 🙈

**Comment by slimline33** [comment]
Hi ich wollte mich nochmal zurück melden.

Ich habe es aufgegeben 😬 und die displays landen im dachboden.... Schade.

**Comment by slimline33** [comment]
Jetzt muss ich es doch wieder aufmachen das issue sorry 🙈 hab mich nochmal durch gerungen und es nochmal versucht. Keine Chance leider.

Wäre es möglich, dass du mir ein Image von deinem esp32 ziehst und das hier zu github hoch laden würdest?

**Comment by slimline33** [comment]
Ich muss mich nochmal melden. Bin jetzt komplett auf OEPL umgestiegen. inzwischen gibt es auch "alpha" firmware status für die subghz chroma displays! Nur für Dich zur Info. 

https://github.com/jjwbruijn/OpenEPaperLink

**Comment by Hades32** [comment]
Cool, Dankeschön. Schau ich mir auf jeden Fall an, wenn ich die Dinger nochmal auspacke
